# 密码123456
# 如果要用加密函数E() 如:E(123456)
# 如果要用解密函数D() 如:D(4x8VBfSLlFy3jvd8R3q5RQ==)
Subscribe: # 订阅配置
  Sub_DN: 'sub.example.com'
  Sub_Vless_Prot: 4333
  Sub_Vmess_Prot: 4334
  Sub_Socks_Prot: 4335
  Sub_UUID: "D(4x8VBfSLlFy3jvd8R3q5RQ==)"
  Sub_Socks_PWD: "D(4x8VBfSLlFy3jvd8R3q5RQ==)"

DDNS: # 解析配置
  AccessKeyID: 'D(XXXXXXXX)'
  AccessKey: 'D(XXXXXXXXXXXXXX)'
  #如: example.com
  DomainName: 'example.com'
  #如: www ,@
  RR: 'www'
  
Wake-on-LAN: # 网络唤醒配置
  #局域网广播地址
  IP: 10.10.10.255
  #唤醒MAC地址
  电脑: 'XX:XX:XX:XX:XX:XX'
  NAS: 'XX:XX:XX:XX:XX:XX'
  
Port: # 端口配置
  #如 OPENWRT: 80
  OPENWRT: 80
Message: 
  测试: '这是测试返回文本'