name: Actions GitHub Workflow
on:
  workflow_call:
  schedule:
    - cron: "0 16 * * 0"
  workflow_dispatch:

jobs:
  del_Workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for current repo
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ipkg|Workflow|pages
          #retain_days: 1
          keep_minimum_runs: 0
          use_daily_retention: true