name: Actions GitHub Workflow

no:
  workflow_call:
    inputs:
      reuse:
        required: false
        type: boolean
        default: false  
  workflow_dispatch:

jobs:
  jod_del:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Call Delete workflow
        if: (inputs.reuse == true)
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: ipkg|Workflow|pages
          #retain_days: 1
          keep_minimum_runs: 0
          use_daily_retention: true
          
      - name: Delete workflow
        if: (inputs.reuse == false)
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 5
          use_daily_retention: true