name: Actions Build gh-action-sdk package ${{ inputs.package_name }}

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      cache:
        description: |
          是否清理缓存?
        required: false
        default: false
        type: boolean
        
      package_name:
        description: |
          选择编译插件
        required: false
        default: "all"
        type: choice
        options:
          - all
          - package-api
          - package-sub
          - package-page
          - luci-app-cifs-mount2
          - luci-app-bypass
          - luci-app-unishare
          - luci-app-v2ray-server
          - luci-app-sunpanel
          - sunpanel
          

jobs:
  jod_initial:
    name: Actions Build ${{ inputs.package_name }}
    runs-on: ubuntu-latest
    outputs:
      time: ${{steps.output_time.outputs.time}}
    steps: 
      - name: output Time
        id: output_time
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "time=$(date "+%Y.%m.%d_%H%M%S")" >> $GITHUB_OUTPUT
          
      - name: Delete GitHub Release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: GitHub-Actions_${{ inputs.package_name }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Cleanup GitHub Cache
        if: (inputs.cache == true)
        run: |
          gh cache delete --all --repo 3wlh/Actions-Build_Package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  jobs_build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    needs: jod_initial
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        sdk:
          - openwrt-24.10
          #- SNAPSHOT
    env:
      Time: ${{ needs.jod_initial.outputs.time }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: ${{ inputs.package_name }}
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: |
            bin/packages/${{ matrix.arch }}/packages_ci/*.apk
            bin/packages/riscv64_generic/packages_ci/*.apk
            bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create compress files
        id: files
        continue-on-error: true
        run: |
          if [ "${{ matrix.arch }}" = "riscv64_riscv64" ] && [ "${{ matrix.sdk }}" = "SNAPSHOT" ]; then
            tar -zcvf ${{ inputs.package_name }}-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/riscv64_generic/ packages_ci
          else
            tar -zcvf ${{ inputs.package_name }}-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci
          fi 
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: Upload ${{ inputs.branch }} as release assets
        if: steps.files.outputs.status == 'success'
        uses: ncipollo/release-action@main
        with:
          tag: GitHub-Actions_${{ inputs.package_name }}
          name: ${{ inputs.package_name }}
          artifacts: ${{ inputs.package_name }}-${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz
          body: "## 编译时间：`${{ env.Time }}`"
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}